import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "Booking.com Clone",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico", 
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}

        {/* Footer */}
      </body>
    </html>
  );
}
